# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
   include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
- name: AppDirectory
  value: $(Build.SourcesDirectory)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    set -e
    npm ci --include=dev
    npm run audit
    npm run typecheck
    npm run lint
    npm run build
  displayName: 'Install, audit, check and build'
  workingDirectory: '${{ variables.AppDirectory }}'

- task: PublishBuildArtifacts@1
  displayName: Publish build artefacts
  inputs:
    PathtoPublish: '${{ variables.AppDirectory }}/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
